"""email

Revision ID: cd9fff695d8f
Revises: 7f8e6cd1be74
Create Date: 2022-07-10 13:00:39.019556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9fff695d8f'
down_revision = '7f8e6cd1be74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_timestamp', table_name='posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###
